server:
  port: 8521
  #thtmeleaf设置
spring:
  #i18国际化设置
  messages:
    basename: i18n.login
    #热部署
  devtools:
    restart:
      enabled: true
      exclude: templates/**
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    content-type: text/html
  mvc:
    date-format: yyyy-MM-dd HH:mm
    hiddenmethod:
      filter:
        enabled: true # 开启支持put delet等方式的提交
  #配置数据源
  datasource:
    username: root
    password: username
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/travle?serverTimezone=GMT&characterEncoding=UTF-8&allowMultiQueries=true
  #配置spring boot文件上传大小限制
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

#开启mybatis下划线转驼峰设置
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations:
    - classpath:mybatis/mapper/*.xml
pagehelper:
  helperDialect: mysql
  #RowBounds第一个参数offset当做页码，默认为false
  offsetAsPageNum: true
  #使用RowBounds分页会进行count查询，默认为false
  rowBoundsWithCount: true
  #启用合理化时，如果pageNum<1会查询第一页，如果pageNum>pages会查询最后一页
  reasonable: false
  #支持通过Mapper接口参数来传递分页参数
  supportMethodsArguments: true
  #设置为true时，如果pageSize=0遍历全部结果，相当于没有分页
  pageSizeZero: true
  #映射参数
  params: count=countSql
#打印日志
logging:
  level:
    www.gnawTravle.com.travel: debug
